#######################################################################################
# Book settings
title : AI/ML Documentation
author: Juan Huerta
#logo: '2.png'

# Information about where the book exists on the web
description: >-
  A personal website with data science resources

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/executablebooks/jupyter-book  #if this stops working i cloned the repo personal_projects
  path_to_book                : "mini-book"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex



######################################################################
# HTML-specific settings
html:
  favicon                   : ""  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : false  # Whether to add a link to your repository button
  use_issues_button         : false  # Whether to add an "open an issue" button
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : ""  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis              : false
    utterances              : false

sphinx:
  config:
    html_theme_options:
      show_navbar_depth: 6
      extra_footer: ""  # Will be displayed underneath the footer.
      extra_navbar:   # Will be displayed underneath the left navbar.

#################

#######################################################################################